# Generated by Django 2.2 on 2019-04-23 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("seats", "0002_seed_seats")]

    operations = [
        migrations.AlterField(
            model_name="seat",
            name="booked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="seats",
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
